volumes:
  jornada_static:
    name: jornada_static

networks:
  jornada_backend:
    external: true

services:
  django:
    restart: always
    image: compose-jornada-producao:latest
    build:
      context: ../../
      dockerfile: ./docker/production/Dockerfile.prod
    expose: 
      - 8000
    volumes:
      - "jornada_static:/static"
      - ../../:/app
    environment:
       - PYTHONPATH=/app
       - PATH=${PATH}:/home/python/.local/bin
       - JORNADA_STATIC_ROOT=/static/
       - JORNADA_STATIC_URL=/static/
       - DJANGO_SETTINGS_MODULE=jornada.settings
       - JORNADA_ENV=${JORNADA_ENV}
    networks:
      - jornada_backend
  nginx:
    restart: always
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "jornada_static:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:z"
    depends_on:
      - django
    networks:
      - jornada_backend

  redis:
    restart: always
    image: "redis:alpine"
    networks:
      - jornada_backend