
import random

# SCRIPT QUE MISTURA OS SOBRENOMES DE TODOS OS ADOLESCENTES DA BASE
# SERVE PARA ANONIMIZAR OS NOMES DE FORMA A PRESERVAR A PRIVACIDADE DOS SOCIOEDUCANDOS

# ATENÇÃO!!! NÃO É POSSÍVEL DESFAZER A MISTURA DOS NOMES DEPOIS DE REALIZADA

# COMO UTILIZAR ?
# 3 - docker-compose exec -T django django-admin shell < ../scripts/shuffle_surnames.py



